env:
  es2021: true
  node: true
extends: standard-with-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  "@typescript-eslint/member-delimiter-style":
    - 2
    - multiline:
        delimiter: semi
      singleline:
        delimiter: semi
  semi: off
  "@typescript-eslint/semi": off
